title:              SW Developer
email:              zcx5674@gmail.com
description:        I like to learn and enjoy new skills.
author:             Wonyong Jang
baseurl:            ""
url:                "https://WonYong-Jang.github.io"

# Social Profiles
twitter_username:   
github_username:    WonYong-Jang
facebook_username:  
linkedin_username:  wonyong-jang-3250b4165/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-167454188-1 # out your google-analytics code

# Build settings
markdown: kramdown
highlighter: rouge
paginate:           10
paginate_path:      "/posts/page:num/"
comments: 
    provider: disqus
disqus:
    shortname: zcx6263
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
